-- 0. Auth (인증)
ALTER SEQUENCE IF EXISTS auth_provider_seq INCREMENT BY 1;

-- 1. User (사용자)
ALTER SEQUENCE IF EXISTS users_seq INCREMENT BY 1;

-- 2. Photographer (작가)
ALTER SEQUENCE IF EXISTS photographer_seq INCREMENT BY 1;
ALTER SEQUENCE IF EXISTS photographer_schedule_seq INCREMENT BY 1;

-- 3. Photo (사진)
ALTER SEQUENCE IF EXISTS photo_seq INCREMENT BY 1;
ALTER SEQUENCE IF EXISTS photo_mood_seq INCREMENT BY 1;

-- 4. Mood (무드)
ALTER SEQUENCE IF EXISTS mood_seq INCREMENT BY 1;

-- 5. Place (장소)
ALTER SEQUENCE IF EXISTS available_location_seq INCREMENT BY 1;
ALTER SEQUENCE IF EXISTS place_seq INCREMENT BY 1;

-- 6. Product (상품)
ALTER SEQUENCE IF EXISTS product_seq INCREMENT BY 1;
ALTER SEQUENCE IF EXISTS product_available_location_seq INCREMENT BY 1;
ALTER SEQUENCE IF EXISTS product_option_seq INCREMENT BY 1;
ALTER SEQUENCE IF EXISTS product_photo_seq INCREMENT BY 1;
ALTER SEQUENCE IF EXISTS product_mood_seq INCREMENT BY 1;

-- 7. Portfolio (포트폴리오)
ALTER SEQUENCE IF EXISTS portfolio_seq INCREMENT BY 1;
ALTER SEQUENCE IF EXISTS portfolio_photo_seq INCREMENT BY 1;
ALTER SEQUENCE IF EXISTS portfolio_place_seq INCREMENT BY 1;
ALTER SEQUENCE IF EXISTS portfolio_mood_seq INCREMENT BY 1;

-- 8. Reservation (예약)
ALTER SEQUENCE IF EXISTS reservation_seq INCREMENT BY 1;
ALTER SEQUENCE IF EXISTS reservation_additional_payment_seq INCREMENT BY 1;

-- 9. Wish (위시)
ALTER SEQUENCE IF EXISTS wish_portfolio_seq INCREMENT BY 1;
ALTER SEQUENCE IF EXISTS wish_product_seq INCREMENT BY 1;

-- 10. Review (리뷰)
ALTER SEQUENCE IF EXISTS review_seq INCREMENT BY 1;
ALTER SEQUENCE IF EXISTS review_photo_seq INCREMENT BY 1;

-- 11. Question (질문)
ALTER SEQUENCE IF EXISTS question_seq INCREMENT BY 1;
ALTER SEQUENCE IF EXISTS question_photo_seq INCREMENT BY 1;

-- 12. Curation (큐레이션)
ALTER SEQUENCE IF EXISTS curation_seq INCREMENT BY 1;